// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDAwO2qEdXt_ginCLnQ_72AQQcM6sKFBXI',
    appId: '1:368572733283:web:3ef87558f03e0d38efe556',
    messagingSenderId: '368572733283',
    projectId: 'crypto-list-app-1d147',
    authDomain: 'crypto-list-app-1d147.firebaseapp.com',
    storageBucket: 'crypto-list-app-1d147.firebasestorage.app',
    measurementId: 'G-DDXTSF0PT9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqhsUHdRlx3dlYwwXf5cFi_JBqsiJVh-s',
    appId: '1:368572733283:android:4d4b4add13d0385aefe556',
    messagingSenderId: '368572733283',
    projectId: 'crypto-list-app-1d147',
    storageBucket: 'crypto-list-app-1d147.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLXNkNXhTaP_jAHBN_xnnduLPzzQ1zt0w',
    appId: '1:368572733283:ios:ad720c0919cfc7e7efe556',
    messagingSenderId: '368572733283',
    projectId: 'crypto-list-app-1d147',
    storageBucket: 'crypto-list-app-1d147.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication10',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDLXNkNXhTaP_jAHBN_xnnduLPzzQ1zt0w',
    appId: '1:368572733283:ios:ad720c0919cfc7e7efe556',
    messagingSenderId: '368572733283',
    projectId: 'crypto-list-app-1d147',
    storageBucket: 'crypto-list-app-1d147.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication10',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDAwO2qEdXt_ginCLnQ_72AQQcM6sKFBXI',
    appId: '1:368572733283:web:06a8915ce5e8ce14efe556',
    messagingSenderId: '368572733283',
    projectId: 'crypto-list-app-1d147',
    authDomain: 'crypto-list-app-1d147.firebaseapp.com',
    storageBucket: 'crypto-list-app-1d147.firebasestorage.app',
    measurementId: 'G-91C7FGQ0E0',
  );
}
